package com.ensemble.models;

//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.Table;
//import javax.validation.constraints.NotNull;

import javax.persistence.*;
import javax.validation.constraints.*;//Hibernate Validator
/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 */
@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's email
  @Column
  @NotNull(message = "error.title.notnull")
  @Size(min = 1, max = 30, message = "error.title.size")   
  private String email;
  
  // The user's name
  
  
  
  @Column
  @Size(max = 10, message = "error.description.size") 
  private String name;
  
  @Column
  @NotNull(message = "error.title.notnull")
  @Size(min = 10, max = 10, message = "error.title.length")
  //@Digits(integer = 10, fraction = 0, message="error.title.onlyinteger")
  @Pattern(regexp = "[\\s]*[0-9]*[1-9]+",message="error.title.onlyinteger")
  private String mobno;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  

public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String email, String name,String mobno) {
    this.email = email;
    this.name = name;
    this.mobno=mobno;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }
  

  public String getMobno() {
	return mobno;
}

public void setMobno(String mobno) {
	this.mobno = mobno;
}


} // class User
